# Generated by Django 4.1.3 on 2022-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inward_Outward_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserDesignation', models.CharField(max_length=255)),
                ('UserPwd', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
